[build]
  command = "./build.sh"
  functions = "functions"
  publish = "static"

[build.environment]
  GO_IMPORT_PATH = "github.com/laof/fetch"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200